### ISSUE TITLE
Latest Silabs EmberZNet PRO Zigbee Protocol Stack Software

### ISSUE THREAD

**Issue by mamrai1** [Nerivec/silabs-firmware-builder#45]
Any plans for new firmware based on version 8.2.0.0 or 8.0.3.0?

**Comment by Nerivec** [comment]
Previous version had too many problems, I never did an official release for it.
I haven't looked into the last one yet, released a few days ago (2025.6.0), it's on my todo list (have to check if Z2M needs a compatibility update too since it's a major).

**Comment by Nerivec** [comment]
Since the gap between the last well-tested version and the latest version is widening, I've create a pre-release (allows some testing in Z2M in case anything there needs fixing):
https://github.com/Nerivec/silabs-firmware-builder/releases/tag/v2025.6.0-pre0
But as mentioned, the same problems as described in https://github.com/Nerivec/silabs-firmware-builder/issues/43 are still present, so, not all adapters are available...

CC: @jorisvervuurt

**Comment by jorisvervuurt** [comment]
@Nerivec Cool, I'll see if I can get to testing this next week. By the way, I did notice that Silabs closed some issues regarding the metadata so I'd assume that those issues have been fixed.

**Comment by Nerivec** [comment]
The dev branch of Z2M should have support in the coming days.
Metadata issues from last time appear fixed indeed. Too bad they didn't fix the software flow control too...

**Comment by mamrai1** [comment]
How about the problems with the software flow control? Is it solved? Should I try it on the sonoff stick?

**Comment by Nerivec** [comment]
That's what I mentioned, the problems are still present, so the release excludes all software flow control coordinator firmware.

**Comment by jorisvervuurt** [comment]
> Since the gap between the last well-tested version and the latest version is widening, I've create a pre-release (allows some testing in Z2M in case anything there needs fixing):
> https://github.com/Nerivec/silabs-firmware-builder/releases/tag/v2025.6.0-pre0

@Nerivec Is this still the latest release based on the latest Silabs SDK? I have just upgraded Z2M to the latest stable release which should include support. I can test coordinator firmware (with HW flow control) and router firmwares for SLZB-07 MG24 next weekend. :)

**Comment by Nerivec** [comment]
Yes. I haven't had much time to test it myself... need some stability feedback for sure.

**Comment by jorisvervuurt** [comment]
> Yes. I haven't had much time to test it myself... need some stability feedback for sure.

Just flashed one of my SLZB-07MG24 router dongles with the new bootloader and router firmware:

<img width="1537" height="271" alt="Image" src="https://github.com/user-attachments/assets/1b20fde1-36e0-49b8-8fe1-672b846563f7" />

Interestingly, the `ember-zli` `Get info` option shows v3.01.00?
In the filename as well as in the Firmware file metadata (see above), it says 3.1.0.
Nothing to worry about I guess? Perhaps it's just padded with zeroes.

I did compare it with a couple of my other dongles, which show v3.00.00 so the bootloader definitely was updated:

<img width="631" height="144" alt="Image" src="https://github.com/user-attachments/assets/47e4e4b1-e4fc-47ba-9c6b-46fa1ecf454d" />

I then flashed the new router firmware:

<img width="1477" height="217" alt="Image" src="https://github.com/user-attachments/assets/eb0c2800-7a8b-405d-9ab0-8b3293adc13a" />

After re-interviewing it in Z2M, it is properly connected and identified:

<img width="780" height="793" alt="Image" src="https://github.com/user-attachments/assets/748202fe-28db-4407-970c-7bf9abeceba3" />

**Comment by Nerivec** [comment]
Looks good. I don't think you'd see much trouble with the router firmware in any case (ironically, the underlaying app is likely far better tested than coordinator by silabs since it would affect a vast amount of devices out there - it's the same building blocks of regular routers/end devices)

**Comment by jorisvervuurt** [comment]
Yep, I figured that would be the case. I'll flash all other router dongles as well as the coordinator later today. Fingers crossed. 😄

**Comment by jorisvervuurt** [comment]
@Nerivec I've now updated all router dongles and after updating the bootloader of the coordinator dongle, I updated it's firmware as well:

![Image](https://github.com/user-attachments/assets/d291c73d-a228-45d1-9718-647dbad5a4cb)

Everything seems to be working well and Z2M detects it correctly as running 8.2.0:

<img width="914" height="415" alt="Image" src="https://github.com/user-attachments/assets/24748a99-6143-4114-ad8f-956ca5e39eae" />

Very uneventful so far, which is of course a good thing. 😃 
I'll keep monitoring things the next days.

Thanks again and have a nice Sunday!

**Comment by jorisvervuurt** [comment]
So far everything has been working stable. 😀 

Only one feature request left: it would be nice if the LED on the dongle could be turned off through Z2M. Right now on the router firmware, the green LED is always on and on the SLZB-07MG24 it's super bright (not ideal in a sleeping room).

Would that be hard to add? I know @darkxst had this feature in his router firmware build. 😄

**Comment by jorisvervuurt** [comment]
Still no issues to report; network seems to be very stable with these coordinator and router firmwares!

I have created a new issue for my feature request: #47
